### ISSUE TITLE
clean_catch(year, TAC) Error in clean_catch(year, TAC) : object 'old_catch' not found

### ISSUE THREAD

**Issue by jimianelli** [BenWilliams-NOAA/rockfishr#5]

**Comment by BenWilliams-NOAA** [comment]
`clean_catch` has a "switch" that looks for frozen catch - since this was setup for just northern rockfish it is defaulting to "catch_1961-1992.csv" or a user defined catch file stored in the `data/user_input` folder. 
isn't setup for an assessment without fixed catch at the moment

**Comment by BenWilliams-NOAA** [comment]
just updated so that either no old catch data is added or user input file is provided

**Comment by jimianelli** [comment]
hmm, not seeing a push or new commit here...no biggie...

**Comment by BenWilliams-NOAA** [comment]
doh - wrong branch...
